### ISSUE TITLE
Improve license on footer

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-web#483]
Hi @peters-rebecca ,

To keep track of a small issue. It seems like the license statement has too much in-line css: 

https://github.com/fablabbcn/smartcitizen-web/blob/2aeab92081924c580472fc5e99531285129bd658/src/app/components/footer/footer.html#L41

We can maybe include a stronger message in it regarding the licenses and our open source commitment. Something minor!

**Comment by pral2a** [comment]
@peters-rebecca and @oscgonfer would something like this work? 

_Smart Citizen® embraces openness by design: all content on this page is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. The platform’s software is released under the GNU Affero General Public License v3.0, its core hardware under the CERN Open Hardware License, and its data under the Open Database License—empowering anyone to explore, replicate, and innovate with our tools._
